research_task:
  description: >
    Conduct a thorough research about AI
    Make sure you find any interesting and relevant information given
    the current year is {current_time}.
  expected_output: >
    A list with 4 bullet points of the most relevant information about AI
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section 40 words for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'. Has to be <160 words
  agent: reporting_analyst
